import {
  Injectable,
  BadRequestException,
  NotFoundException,
  InternalServerErrorException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { spawn } from 'child_process';
import * as fs from 'fs/promises';
import * as path from 'path';
import { createReadStream } from 'fs';
import { AuditService } from '../audit/audit.service';
import { AuditAction } from '../audit/audit-log.entity';

const VALID_FILENAME = /^backup_[\d_-]+\.sql\.gz$/;

export interface BackupMeta {
  filename: string;
  size: number;
  sizeMB: string;
  createdAt: Date;
}

@Injectable()
export class BackupService {
  private readonly BACKUP_DIR = '/app/backups';
  private readonly MAX_TOTAL_SIZE = 1024 * 1024 * 1024; // 1 GB

  private readonly dbHost: string;
  private readonly dbName: string;
  private readonly dbUser: string;
  private readonly dbPassword: string;

  constructor(
    private readonly auditService: AuditService,
    private readonly configService: ConfigService,
  ) {
    this.dbHost     = this.configService.get<string>('DB_HOST', 'postgres');
    this.dbName     = this.configService.get<string>('DB_DATABASE', 'medical_db');
    this.dbUser     = this.configService.get<string>('DB_USERNAME', 'medical_user');
    this.dbPassword = this.configService.get<string>('DB_PASSWORD', 'medical123');

    // Ensure backup dir exists on startup
    fs.mkdir(this.BACKUP_DIR, { recursive: true }).catch(() => {});
  }

  // ─── List ──────────────────────────────────────────────────────────────────

  async listBackups(): Promise<{
    items: BackupMeta[];
    total: number;
    totalSize: number;
    totalSizeMB: string;
    maxSize: number;
  }> {
    try {
      await fs.mkdir(this.BACKUP_DIR, { recursive: true });
      const files = await fs.readdir(this.BACKUP_DIR);
      const metas = await Promise.all(
        files
          .filter(f => VALID_FILENAME.test(f))
          .map(async (filename) => {
            const filepath = path.join(this.BACKUP_DIR, filename);
            const stats = await fs.stat(filepath);
            return {
              filename,
              size: stats.size,
              sizeMB: (stats.size / 1024 / 1024).toFixed(2),
              createdAt: stats.mtime,
            } as BackupMeta;
          }),
      );
      metas.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
      const totalSize = metas.reduce((s, m) => s + m.size, 0);
      return {
        items: metas,
        total: metas.length,
        totalSize,
        totalSizeMB: (totalSize / 1024 / 1024).toFixed(2),
        maxSize: this.MAX_TOTAL_SIZE,
      };
    } catch {
      return { items: [], total: 0, totalSize: 0, totalSizeMB: '0', maxSize: this.MAX_TOTAL_SIZE };
    }
  }

  // ─── Create ────────────────────────────────────────────────────────────────

  async createBackup(userId: number, ip?: string): Promise<{ filename: string; size: number; sizeMB: string }> {
    await fs.mkdir(this.BACKUP_DIR, { recursive: true });

    // Filename ALWAYS generated by backend — never user input
    const ts = new Date()
      .toISOString()
      .replace('T', '_')
      .replace(/:/g, '-')
      .substring(0, 19);
    const filename = `backup_${ts}.sql.gz`;
    const filepath = path.join(this.BACKUP_DIR, filename);

    return new Promise((resolve, reject) => {
      const pgEnv = { ...process.env, PGPASSWORD: this.dbPassword };

      // spawn with array args — NO shell, NO injection risk
      const pgDump = spawn(
        'pg_dump',
        [
          '-h', this.dbHost,
          '-U', this.dbUser,
          '-d', this.dbName,
          '--no-owner',
          '--clean',
          '--if-exists',
        ],
        { env: pgEnv },
      );

      const gzip = spawn('gzip', ['-c']);
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const writeStream = require('fs').createWriteStream(filepath);

      pgDump.stdout.pipe(gzip.stdin);
      gzip.stdout.pipe(writeStream);

      let pgErr = '';
      pgDump.stderr.on('data', (d: Buffer) => { pgErr += d.toString(); });

      let pgExitCode: number | null = null;
      pgDump.on('exit', (code) => { pgExitCode = code; });

      writeStream.on('finish', async () => {
        if (pgExitCode !== 0) {
          // Clean up the partial file
          await fs.unlink(filepath).catch(() => {});
          await this.auditService.log({
            userId, action: AuditAction.CREATE, resource: 'backup',
            method: 'POST', endpoint: '/api/backup/create',
            ip, success: false,
            description: 'pg_dump failed',
            errorMessage: pgErr.substring(0, 500),
          });
          reject(new InternalServerErrorException('pg_dump failed: ' + pgErr.substring(0, 200)));
          return;
        }

        const stats = await fs.stat(filepath);
        const sizeMB = (stats.size / 1024 / 1024).toFixed(2);

        await this.auditService.log({
          userId, action: AuditAction.CREATE, resource: 'backup',
          method: 'POST', endpoint: '/api/backup/create',
          ip, success: true,
          description: `Created backup ${filename} (${sizeMB} MB)`,
        });

        await this.cleanupOldBackups();
        resolve({ filename, size: stats.size, sizeMB });
      });

      pgDump.on('error', (err) => reject(new InternalServerErrorException('pg_dump error: ' + err.message)));
      gzip.on('error',   (err) => reject(new InternalServerErrorException('gzip error: ' + err.message)));
      writeStream.on('error', (err: Error) => reject(new InternalServerErrorException('write error: ' + err.message)));
    });
  }

  // ─── Download stream ───────────────────────────────────────────────────────

  async getBackupStream(filename: string) {
    this.validateFilename(filename);
    const filepath = path.join(this.BACKUP_DIR, filename);
    try {
      await fs.access(filepath);
    } catch {
      throw new NotFoundException('Backup not found');
    }
    const stats = await fs.stat(filepath);
    return { stream: createReadStream(filepath), size: stats.size };
  }

  // ─── Delete ────────────────────────────────────────────────────────────────

  async deleteBackup(filename: string, userId: number, ip?: string): Promise<{ success: boolean }> {
    this.validateFilename(filename);
    const filepath = path.join(this.BACKUP_DIR, filename);
    try {
      await fs.unlink(filepath);
    } catch {
      throw new NotFoundException('Backup not found');
    }
    await this.auditService.log({
      userId, action: AuditAction.DELETE, resource: 'backup',
      method: 'DELETE', endpoint: `/api/backup/${filename}`,
      ip, success: true,
      description: `Deleted backup ${filename}`,
    });
    return { success: true };
  }

  // ─── Restore ───────────────────────────────────────────────────────────────

  async restoreBackup(filename: string, userId: number, ip?: string): Promise<{ success: boolean }> {
    this.validateFilename(filename);
    const filepath = path.join(this.BACKUP_DIR, filename);
    try {
      await fs.access(filepath);
    } catch {
      throw new NotFoundException('Backup not found');
    }

    return new Promise((resolve, reject) => {
      const pgEnv = { ...process.env, PGPASSWORD: this.dbPassword };

      // gunzip -c <file> | psql  — both with array args
      const gunzip = spawn('gunzip', ['-c', filepath]);
      const psql = spawn(
        'psql',
        ['-h', this.dbHost, '-U', this.dbUser, '-d', this.dbName],
        { env: pgEnv },
      );

      gunzip.stdout.pipe(psql.stdin);

      let psqlErr = '';
      psql.stderr.on('data', (d: Buffer) => { psqlErr += d.toString(); });

      psql.on('exit', async (code) => {
        const success = code === 0;
        await this.auditService.log({
          userId, action: AuditAction.UPDATE, resource: 'backup',
          method: 'POST', endpoint: `/api/backup/restore/${filename}`,
          ip, success,
          description: success
            ? `RESTORED database from ${filename}`
            : `FAILED restore from ${filename}`,
          ...(success ? {} : { errorMessage: psqlErr.substring(0, 500) }),
        });
        if (success) {
          resolve({ success: true });
        } else {
          reject(new InternalServerErrorException('Restore failed: ' + psqlErr.substring(0, 200)));
        }
      });

      gunzip.on('error', (err) => reject(new InternalServerErrorException('gunzip error: ' + err.message)));
      psql.on('error',   (err) => reject(new InternalServerErrorException('psql error: ' + err.message)));
    });
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  private validateFilename(filename: string): void {
    if (!VALID_FILENAME.test(filename)) {
      throw new BadRequestException('Invalid backup filename');
    }
  }

  private async cleanupOldBackups(): Promise<void> {
    const { items, totalSize } = await this.listBackups();
    if (totalSize <= this.MAX_TOTAL_SIZE) return;

    const ascending = [...items].reverse(); // oldest first
    let current = totalSize;

    for (const b of ascending) {
      if (current <= this.MAX_TOTAL_SIZE) break;
      try {
        await fs.unlink(path.join(this.BACKUP_DIR, b.filename));
        current -= b.size;
        console.log(`[BackupService] Auto-cleanup: removed ${b.filename}`);
      } catch (e: any) {
        console.error(`[BackupService] Cleanup failed for ${b.filename}:`, e?.message);
      }
    }
  }
}
